/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CustomizationRequest = IDL.Record({
  'designIdentifier' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'details' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRequestsByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(CustomizationRequest)],
      ['query'],
    ),
  'getRequest' : IDL.Func([IDL.Text], [CustomizationRequest], ['query']),
  'submitRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CustomizationRequest = IDL.Record({
    'designIdentifier' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRequestsByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(CustomizationRequest)],
        ['query'],
      ),
    'getRequest' : IDL.Func([IDL.Text], [CustomizationRequest], ['query']),
    'submitRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };